title: The Rishi Zone
markdown: kramdown

# for atom feed
author:
  name: Rishi Israni
  email: rishi@sanjobanjo.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

url: https://RishiMakesThings.github.io  # the base hostname and protocol for your site, e.g. http://example.com

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
